config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :juices
end

app/models/juice.rb
class Juice < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/juices_controller.rb
class JuicesController < ApplicationController

  def index
    @juice = Juice.new
    @juices = Juice.all
  end

  def create
    @juice = Juice.create(juice_params)
    if @juice.save
      redirect_to juices_path
    else
      render :index
    end
  end

  def show
    @juice = Juice.find(params[:id])
  end

  def edit
    @juice = Juice.find(params[:id])
  end

  def update
    @juice = Juice.find(params[:id])
    @juice.update_attributes!(juice_params)

    redirect_to juices_path
  end

  def destroy
    @juice = Juice.find(params[:id]).delete

    redirect_to juices_path
  end

  private

  def juice_params
    params.require(:juice).permit(:flavor, :ingredients)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/juices/edit.html.erb
<%= form_for @juice do |f| %>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/juices/index.html.erb
<%= form_for @juice do |f| %>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.label :ingredients %>
    <%= f.text_field :ingredients %>
  </p>
  <p>
    <%= f.submit 'Create juice' %>
  </p>
<% end %>

<% @juices.each do |juice| %>
<ul>
  <li>
    <%= juice.flavor %><br>
  <%= juice.ingredients %>
  </li>
</ul>
<% end %>

app/views/juices/show.html.erb
<ul>
  <li>
    <%= @juice.flavor %>
    <br>
    <%= @juice.ingredients %>
  </li>
</ul>

<%= link_to 'Edit', edit_juice_path %>
<%= link_to 'Delete', juice_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudJuices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add juice', juices_path %>